---
title: "Lecture tidy data and relational datasets"
author: "Yao"
date: "2025-09-23"
output: html_document
---

```{r echo = FALSE, message = FALSE}
library(tidyverse)

library(haven)
```

## pivot_longer
```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()

view(pulse_df)
```

```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi")

pulse_tidy_df
```

```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi")

pulse_tidy_df
```


## Pivot wider
```{r}

analysis_df = 
```

```{r}
fellowship_ring = 
  readxl::read_excel("/Users/air/Desktop/Data Science 1/data_import_examples/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")
fellowship_ring

two_towers = 
  readxl::read_excel("/Users/air/Desktop/Data Science 1/data_import_examples/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")
two_towers

return_king = 
  
  
```

## Join FAS datasets
Import 'litters' dataset.
```{r}

litters_df =
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", " ")) |>
  janitor::clean_names() |>
  mutate(wt_gain = gd18_weight - gd0_weight) |>
  separate(
    group, into = c("dose", "day_of_treatment"), sep = 3
  )



```

Import 'pups' next!
```{r}

pups_df = 
  read_csv("/Users/air/Desktop/Data Science 1/data_import_examples/FAS_pups.csv", 
           na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  mutate(
    sex = case_match(
      sex,
      1 ~ "male",
      2~ "female"
    )
  )
```

Join the datasets!
```{r}

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")

```

