---
title: "20250925 Lecture Visualization 1"
author: "Yao"
date: "2025-09-25"
output: github_document
---


```{r include=FALSE}
library(tidyverse)
library(ggridges)
library(p8105.datasets)
```

Import the weather data

```{r}
data("weather_df")
```

Making our first plot
```{r echo=FALSE}

ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()


```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
ggp_weather_scatterplot = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggp_weather_scatterplot

```

Check that some rows are missing.
```{r}
weather_df |>
  filter(is.na(tmax))

```

## Fancier scatterplots
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  geom_smooth(se = FALSE) # remove shadow

```

Where you define aesthetics can matter
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(aes(color = name), alpha = 0.3, size = 0.6) + # size makes points bigger/smaller
  #geom_point(aes(color = name, size = prcp), alpha = 0.3) + # size points as percentage
  geom_smooth(se = FALSE) # remove shadow
 
```

use faceting real quick
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) + 
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) + 
  geom_smooth(se = FALSE) + 
  facet_grid(name ~ .) # plots separate by name
```

Let's make a somewhat more interesting scatterplot
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(aes(size = prcp), alpha = 0.3) + 
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

LA plot:
```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax_fahr = tmax * (9/5) + 32,
    tmin_fahr = tmin * (9/5) + 32
  ) |>
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) + 
    geom_point() + 
    geom_smooth(se = FALSE, method = "lm") #method lm: linear regression

```

## Small things
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  #geom_point(alpha = 0.3) + 
  geom_smooth(se = FALSE)

weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_smooth(se = FALSE) +
  geom_point()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex() #show density: where the points are most

```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(color = "purple")

```

## Univariate plots
```{r}
weather_df |>
  ggplot(aes(x = tmin)) + #histogram no need y
  geom_histogram(color = "white", fill = "red") #color is the bound outside, fill is inside

```

```{r}
weather_df |>
  ggplot(aes(x = tmin, color = name)) + 
  geom_histogram()

weather_df |>
  ggplot(aes(x = tmin, fill = name)) + 
  geom_histogram()
```

how would i fill 
```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) + 
  geom_histogram()
  facet_grid(name ~ .)
```

maybe a density plot
```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) + 
  geom_density(alpha = 0.2)
```

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin)) + 
    geom_boxplot(aes(fill = name))

```

violin plots
```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin, fill = name)) + 
    geom_violin() #vertical shape density plot
```

ridge plot
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = name)) + 
  geom_density_ridges()

```

LA univariate plots
```{r}

```

